import random
import string

#default length 10 if no value provided 
def generate_password(length: int = 10):
    alphabet = string.ascii_letters + string.digits + string.punctuation #pool of characters can use for password
    password = ''.join(random.choice(alphabet) for i in range(length)) #random characters generated by loop are combined into single string
    return password

password = generate_password()
print(f"Generated Password: {password}")